config/routes.rb
Rails.application.routes.draw do

  resources :users, :path => "usuarios"
  resources :roles, :path => "roles"
  resources :cities, :path => "ciudades"
  resources :departments, :path => "departamentos"
  resources :countries, :path => "paises"
  resources :arles, :path => "arls"
  resources :epses, :path => "eps"
  get 'reset_passwords/new'

  get 'pages/home'
  get 'pages/contact'
  get 'pages/help'

  root to: 'pages#home'

  resources :patients , :path => "pascientes" do
         resources :clinic_histories, :path => "historias_clinicas"
      member do
      get :activate
    end
  end

  resources :clinic_histories, :path => "historias_clinicas" do
          resources :personal_histories, :path => "historias_personales"
          resources :system_reviews, :path => "revision_por_sistemas"
          resources :physical_exams, :path => "examenes_fisicos"
          resources :additional_informations, :path => "informacion_adicional"
      end 
  
  resources :products
  resources :sessions
  resources :reset_passwords, only: [:new, :create, :update, :edit]

  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      post :empty_trash
    end
  end

  get       'signup', to:   'users#new',  as: :signup
  get       'login',  to:   'sessions#new',       as: :login
  post      'login',  to:   'sessions#create'
  delete    'logout', to:   'sessions#destroy',   as: :logout

end

app/models/physical_exam.rb
class PhysicalExam < ActiveRecord::Base
	  belongs_to :clinic_history
end

app/controllers/physical_exams_controller.rb
class PhysicalExamsController < ApplicationController
  # before_action :set_physical_exam, only: [:show, :edit, :update, :destroy]
  before_action :set_member
  # GET /physical_exams
  # GET /physical_exams.json
  def index
    @physical_exams = @clinic_history.physical_exams.all
  end

  # GET /physical_exams/1
  # GET /physical_exams/1.json
  def show
  end

  # GET /physical_exams/new
  def new
    @physical_exam = PhysicalExam.new
  end

  # GET /physical_exams/1/edit
  def edit
  end

  # POST /physical_exams
  # POST /physical_exams.json
  def create
    @physical_exam = PhysicalExam.new(physical_exam_params)
    @physical_exam.clinic_history_id = @clinic_history.id



    respond_to do |format|
      if @physical_exam.save
        format.html { redirect_to new_clinic_history_additional_information_path, notice: 'Physical exam was successfully created.' }
        format.json { render :show, status: :created, location: @physical_exam }
      else
        format.html { render :new }
        format.json { render json: @physical_exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physical_exams/1
  # PATCH/PUT /physical_exams/1.json
  def update
    respond_to do |format|
      if @physical_exam.update(physical_exam_params)
        format.html { redirect_to clinic_history_physical_exams_path(@clinic_history, @physical_exam), notice: 'Physical exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @physical_exam }
      else
        format.html { render :edit }
        format.json { render json: @physical_exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physical_exams/1
  # DELETE /physical_exams/1.json
  def destroy
    @physical_exam.destroy
    respond_to do |format|
      format.html { redirect_to clinic_history_physical_exams_path(@clinic_history, @physical_exam), notice: 'System review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.

    def set_member
      @clinic_history = ClinicHistory.find(params[:clinic_history_id])
      @physical_exam = PhysicalExam.find(params[:id]) if params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def physical_exam_params
      params.require(:physical_exam).permit(:ta_mmgh, :heart_rate, :breathing_frequency, :sat_of_o_ambiente, :sat_of_o_supplementary, :temperature, :weight, :in, :kilograms, :height_in_centimeters, :glucose, :measurement, :head, :head_description, :sense_organ, :sense_organ_description, :neck, :neck_description, :rib_cage, :rib_cage_description, :heart, :heart_description, :lungs, :lungs_description, :abdomen, :abdomen_description, :genitourinary, :genitourinary_description, :rectum, :rectum_description, :extremities, :extremities_description, :skin_and_appendages, :skin_and_appendages_description, :skeletal_muscle, :skeletal_muscle_description, :mental, :mental_description, :neurological, :neurological_description, :alteration, :eye_opening, :verbal_answer, :motor_response, :other_signs)
    end
end

app/helpers/physical_exams_helper.rb
module PhysicalExamsHelper
end

app/views/physical_exams/_form.html.erb
<button><a href="javascript:history.back()">Revision por sistema</a> </button>


<script>
function goBack() {
    window.history.go(+1);
}
</script>
<button onclick="goBack()">Información adicional</button>




<%= simple_form_for [@clinic_history, @physical_exam], :html => { :class => 'form-horizontal' } do |f| %>

  <%= f.input :ta_mmgh %>
  <%= error_span(@physical_exam[:ta_mmgh]) %>
  <%= f.input :heart_rate %>
  <%= error_span(@physical_exam[:heart_rate]) %>
  <%= f.input :breathing_frequency %>
  <%= error_span(@physical_exam[:breathing_frequency]) %>
  <%= f.input :sat_of_o_ambiente %>
  <%= error_span(@physical_exam[:sat_of_o_ambiente]) %>
  <%= f.input :sat_of_o_supplementary %>
  <%= error_span(@physical_exam[:sat_of_o_supplementary]) %>
  <%= f.input :temperature %>
  <%= error_span(@physical_exam[:temperature]) %>
  <%= f.input :weight %>
  <%= error_span(@physical_exam[:weight]) %>
  <%= f.input :in %>
  <%= error_span(@physical_exam[:in]) %>
  <%= f.input :kilograms %>
  <%= error_span(@physical_exam[:kilograms]) %>
  <%= f.input :height_in_centimeters %>
  <%= error_span(@physical_exam[:height_in_centimeters]) %>
  <%= f.input :glucose %>
  <%= error_span(@physical_exam[:glucose]) %>
  <%= f.input :measurement %>
  <%= error_span(@physical_exam[:measurement]) %>
  <%= f.input :head %>
  <%= error_span(@physical_exam[:head]) %>
  <%= f.input :head_description %>
  <%= error_span(@physical_exam[:head_description]) %>
  <%= f.input :sense_organ %>
  <%= error_span(@physical_exam[:sense_organ]) %>
  <%= f.input :sense_organ_description %>
  <%= error_span(@physical_exam[:sense_organ_description]) %>
  <%= f.input :neck %>
  <%= error_span(@physical_exam[:neck]) %>
  <%= f.input :neck_description %>
  <%= error_span(@physical_exam[:neck_description]) %>
  <%= f.input :rib_cage %>
  <%= error_span(@physical_exam[:rib_cage]) %>
  <%= f.input :rib_cage_description %>
  <%= error_span(@physical_exam[:rib_cage_description]) %>
  <%= f.input :heart %>
  <%= error_span(@physical_exam[:heart]) %>
  <%= f.input :heart_description %>
  <%= error_span(@physical_exam[:heart_description]) %>
  <%= f.input :lungs %>
  <%= error_span(@physical_exam[:lungs]) %>
  <%= f.input :lungs_description %>
  <%= error_span(@physical_exam[:lungs_description]) %>
  <%= f.input :abdomen %>
  <%= error_span(@physical_exam[:abdomen]) %>
  <%= f.input :abdomen_description %>
  <%= error_span(@physical_exam[:abdomen_description]) %>
  <%= f.input :genitourinary %>
  <%= error_span(@physical_exam[:genitourinary]) %>
  <%= f.input :genitourinary_description %>
  <%= error_span(@physical_exam[:genitourinary_description]) %>
  <%= f.input :rectum %>
  <%= error_span(@physical_exam[:rectum]) %>
  <%= f.input :rectum_description %>
  <%= error_span(@physical_exam[:rectum_description]) %>
  <%= f.input :extremities %>
  <%= error_span(@physical_exam[:extremities]) %>
  <%= f.input :extremities_description %>
  <%= error_span(@physical_exam[:extremities_description]) %>
  <%= f.input :skin_and_appendages %>
  <%= error_span(@physical_exam[:skin_and_appendages]) %>
  <%= f.input :skin_and_appendages_description %>
  <%= error_span(@physical_exam[:skin_and_appendages_description]) %>
  <%= f.input :skeletal_muscle %>
  <%= error_span(@physical_exam[:skeletal_muscle]) %>
  <%= f.input :skeletal_muscle_description %>
  <%= error_span(@physical_exam[:skeletal_muscle_description]) %>
  <%= f.input :mental %>
  <%= error_span(@physical_exam[:mental]) %>
  <%= f.input :mental_description %>
  <%= error_span(@physical_exam[:mental_description]) %>
  <%= f.input :neurological %>
  <%= error_span(@physical_exam[:neurological]) %>
  <%= f.input :neurological_description %>
  <%= error_span(@physical_exam[:neurological_description]) %>
  <%= f.input :alteration %>
  <%= error_span(@physical_exam[:alteration]) %>
  <%= f.input :eye_opening %>
  <%= error_span(@physical_exam[:eye_opening]) %>
  <%= f.input :verbal_answer %>
  <%= error_span(@physical_exam[:verbal_answer]) %>
  <%= f.input :motor_response %>
  <%= error_span(@physical_exam[:motor_response]) %>
  <%= f.input :other_signs %>
  <%= error_span(@physical_exam[:other_signs]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                clinic_history_physical_exams_path(@clinic_history), :class => 'btn btn-default' %>
<% end %>

app/views/physical_exams/edit.html.erb
<%- model_class = PhysicalExam -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/physical_exams/index.html.erb
<%- model_class = PhysicalExam -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:ta_mmgh) %></th>
      <th><%= model_class.human_attribute_name(:heart_rate) %></th>
      <th><%= model_class.human_attribute_name(:breathing_frequency) %></th>
      <th><%= model_class.human_attribute_name(:sat_of_o_ambiente) %></th>
      <th><%= model_class.human_attribute_name(:sat_of_o_supplementary) %></th>
      <th><%= model_class.human_attribute_name(:temperature) %></th>
      <th><%= model_class.human_attribute_name(:weight) %></th>
      <th><%= model_class.human_attribute_name(:in) %></th>
      <th><%= model_class.human_attribute_name(:kilograms) %></th>
      <th><%= model_class.human_attribute_name(:height_in_centimeters) %></th>
      <th><%= model_class.human_attribute_name(:glucose) %></th>
      <th><%= model_class.human_attribute_name(:measurement) %></th>
      <th><%= model_class.human_attribute_name(:head) %></th>
      <th><%= model_class.human_attribute_name(:head_description) %></th>
      <th><%= model_class.human_attribute_name(:sense_organ) %></th>
      <th><%= model_class.human_attribute_name(:sense_organ_description) %></th>
      <th><%= model_class.human_attribute_name(:neck) %></th>
      <th><%= model_class.human_attribute_name(:neck_description) %></th>
      <th><%= model_class.human_attribute_name(:rib_cage) %></th>
      <th><%= model_class.human_attribute_name(:rib_cage_description) %></th>
      <th><%= model_class.human_attribute_name(:heart) %></th>
      <th><%= model_class.human_attribute_name(:heart_description) %></th>
      <th><%= model_class.human_attribute_name(:lungs) %></th>
      <th><%= model_class.human_attribute_name(:lungs_description) %></th>
      <th><%= model_class.human_attribute_name(:abdomen) %></th>
      <th><%= model_class.human_attribute_name(:abdomen_description) %></th>
      <th><%= model_class.human_attribute_name(:genitourinary) %></th>
      <th><%= model_class.human_attribute_name(:genitourinary_description) %></th>
      <th><%= model_class.human_attribute_name(:rectum) %></th>
      <th><%= model_class.human_attribute_name(:rectum_description) %></th>
      <th><%= model_class.human_attribute_name(:extremities) %></th>
      <th><%= model_class.human_attribute_name(:extremities_description) %></th>
      <th><%= model_class.human_attribute_name(:skin_and_appendages) %></th>
      <th><%= model_class.human_attribute_name(:skin_and_appendages_description) %></th>
      <th><%= model_class.human_attribute_name(:skeletal_muscle) %></th>
      <th><%= model_class.human_attribute_name(:skeletal_muscle_description) %></th>
      <th><%= model_class.human_attribute_name(:mental) %></th>
      <th><%= model_class.human_attribute_name(:mental_description) %></th>
      <th><%= model_class.human_attribute_name(:neurological) %></th>
      <th><%= model_class.human_attribute_name(:neurological_description) %></th>
      <th><%= model_class.human_attribute_name(:alteration) %></th>
      <th><%= model_class.human_attribute_name(:eye_opening) %></th>
      <th><%= model_class.human_attribute_name(:verbal_answer) %></th>
      <th><%= model_class.human_attribute_name(:motor_response) %></th>
      <th><%= model_class.human_attribute_name(:other_signs) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @physical_exams.each do |physical_exam| %>
      <tr>
        <td><%= link_to physical_exam.id, physical_exam_path(physical_exam) %></td>
        <td><%= physical_exam.ta_mmgh %></td>
        <td><%= physical_exam.heart_rate %></td>
        <td><%= physical_exam.breathing_frequency %></td>
        <td><%= physical_exam.sat_of_o_ambiente %></td>
        <td><%= physical_exam.sat_of_o_supplementary %></td>
        <td><%= physical_exam.temperature %></td>
        <td><%= physical_exam.weight %></td>
        <td><%= physical_exam.in %></td>
        <td><%= physical_exam.kilograms %></td>
        <td><%= physical_exam.height_in_centimeters %></td>
        <td><%= physical_exam.glucose %></td>
        <td><%= physical_exam.measurement %></td>
        <td><%= physical_exam.head %></td>
        <td><%= physical_exam.head_description %></td>
        <td><%= physical_exam.sense_organ %></td>
        <td><%= physical_exam.sense_organ_description %></td>
        <td><%= physical_exam.neck %></td>
        <td><%= physical_exam.neck_description %></td>
        <td><%= physical_exam.rib_cage %></td>
        <td><%= physical_exam.rib_cage_description %></td>
        <td><%= physical_exam.heart %></td>
        <td><%= physical_exam.heart_description %></td>
        <td><%= physical_exam.lungs %></td>
        <td><%= physical_exam.lungs_description %></td>
        <td><%= physical_exam.abdomen %></td>
        <td><%= physical_exam.abdomen_description %></td>
        <td><%= physical_exam.genitourinary %></td>
        <td><%= physical_exam.genitourinary_description %></td>
        <td><%= physical_exam.rectum %></td>
        <td><%= physical_exam.rectum_description %></td>
        <td><%= physical_exam.extremities %></td>
        <td><%= physical_exam.extremities_description %></td>
        <td><%= physical_exam.skin_and_appendages %></td>
        <td><%= physical_exam.skin_and_appendages_description %></td>
        <td><%= physical_exam.skeletal_muscle %></td>
        <td><%= physical_exam.skeletal_muscle_description %></td>
        <td><%= physical_exam.mental %></td>
        <td><%= physical_exam.mental_description %></td>
        <td><%= physical_exam.neurological %></td>
        <td><%= physical_exam.neurological_description %></td>
        <td><%= physical_exam.alteration %></td>
        <td><%= physical_exam.eye_opening %></td>
        <td><%= physical_exam.verbal_answer %></td>
        <td><%= physical_exam.motor_response %></td>
        <td><%= physical_exam.other_signs %></td>
        <td><%=l physical_exam.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_physical_exam_path(physical_exam), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      physical_exam_path(physical_exam),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to t('.new', :default => t("helpers.links.new")),
            new_clinic_history_physical_exam_path(@clinic_history, @patient),
            :class => 'btn btn-primary' %> | 
<%= link_to t('.back', :default => t("helpers.links.back")),
            patients_path,
            :class => 'btn btn-inverse' %>

app/views/physical_exams/new.html.erb
<%- model_class = PhysicalExam -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/physical_exams/show.html.erb
<%- model_class = PhysicalExam -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:ta_mmgh) %>:</strong></dt>
  <dd><%= @physical_exam.ta_mmgh %></dd>
  <dt><strong><%= model_class.human_attribute_name(:heart_rate) %>:</strong></dt>
  <dd><%= @physical_exam.heart_rate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:breathing_frequency) %>:</strong></dt>
  <dd><%= @physical_exam.breathing_frequency %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sat_of_o_ambiente) %>:</strong></dt>
  <dd><%= @physical_exam.sat_of_o_ambiente %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sat_of_o_supplementary) %>:</strong></dt>
  <dd><%= @physical_exam.sat_of_o_supplementary %></dd>
  <dt><strong><%= model_class.human_attribute_name(:temperature) %>:</strong></dt>
  <dd><%= @physical_exam.temperature %></dd>
  <dt><strong><%= model_class.human_attribute_name(:weight) %>:</strong></dt>
  <dd><%= @physical_exam.weight %></dd>
  <dt><strong><%= model_class.human_attribute_name(:in) %>:</strong></dt>
  <dd><%= @physical_exam.in %></dd>
  <dt><strong><%= model_class.human_attribute_name(:kilograms) %>:</strong></dt>
  <dd><%= @physical_exam.kilograms %></dd>
  <dt><strong><%= model_class.human_attribute_name(:height_in_centimeters) %>:</strong></dt>
  <dd><%= @physical_exam.height_in_centimeters %></dd>
  <dt><strong><%= model_class.human_attribute_name(:glucose) %>:</strong></dt>
  <dd><%= @physical_exam.glucose %></dd>
  <dt><strong><%= model_class.human_attribute_name(:measurement) %>:</strong></dt>
  <dd><%= @physical_exam.measurement %></dd>
  <dt><strong><%= model_class.human_attribute_name(:head) %>:</strong></dt>
  <dd><%= @physical_exam.head %></dd>
  <dt><strong><%= model_class.human_attribute_name(:head_description) %>:</strong></dt>
  <dd><%= @physical_exam.head_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sense_organ) %>:</strong></dt>
  <dd><%= @physical_exam.sense_organ %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sense_organ_description) %>:</strong></dt>
  <dd><%= @physical_exam.sense_organ_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:neck) %>:</strong></dt>
  <dd><%= @physical_exam.neck %></dd>
  <dt><strong><%= model_class.human_attribute_name(:neck_description) %>:</strong></dt>
  <dd><%= @physical_exam.neck_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rib_cage) %>:</strong></dt>
  <dd><%= @physical_exam.rib_cage %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rib_cage_description) %>:</strong></dt>
  <dd><%= @physical_exam.rib_cage_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:heart) %>:</strong></dt>
  <dd><%= @physical_exam.heart %></dd>
  <dt><strong><%= model_class.human_attribute_name(:heart_description) %>:</strong></dt>
  <dd><%= @physical_exam.heart_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lungs) %>:</strong></dt>
  <dd><%= @physical_exam.lungs %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lungs_description) %>:</strong></dt>
  <dd><%= @physical_exam.lungs_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:abdomen) %>:</strong></dt>
  <dd><%= @physical_exam.abdomen %></dd>
  <dt><strong><%= model_class.human_attribute_name(:abdomen_description) %>:</strong></dt>
  <dd><%= @physical_exam.abdomen_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:genitourinary) %>:</strong></dt>
  <dd><%= @physical_exam.genitourinary %></dd>
  <dt><strong><%= model_class.human_attribute_name(:genitourinary_description) %>:</strong></dt>
  <dd><%= @physical_exam.genitourinary_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rectum) %>:</strong></dt>
  <dd><%= @physical_exam.rectum %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rectum_description) %>:</strong></dt>
  <dd><%= @physical_exam.rectum_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:extremities) %>:</strong></dt>
  <dd><%= @physical_exam.extremities %></dd>
  <dt><strong><%= model_class.human_attribute_name(:extremities_description) %>:</strong></dt>
  <dd><%= @physical_exam.extremities_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:skin_and_appendages) %>:</strong></dt>
  <dd><%= @physical_exam.skin_and_appendages %></dd>
  <dt><strong><%= model_class.human_attribute_name(:skin_and_appendages_description) %>:</strong></dt>
  <dd><%= @physical_exam.skin_and_appendages_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:skeletal_muscle) %>:</strong></dt>
  <dd><%= @physical_exam.skeletal_muscle %></dd>
  <dt><strong><%= model_class.human_attribute_name(:skeletal_muscle_description) %>:</strong></dt>
  <dd><%= @physical_exam.skeletal_muscle_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mental) %>:</strong></dt>
  <dd><%= @physical_exam.mental %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mental_description) %>:</strong></dt>
  <dd><%= @physical_exam.mental_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:neurological) %>:</strong></dt>
  <dd><%= @physical_exam.neurological %></dd>
  <dt><strong><%= model_class.human_attribute_name(:neurological_description) %>:</strong></dt>
  <dd><%= @physical_exam.neurological_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:alteration) %>:</strong></dt>
  <dd><%= @physical_exam.alteration %></dd>
  <dt><strong><%= model_class.human_attribute_name(:eye_opening) %>:</strong></dt>
  <dd><%= @physical_exam.eye_opening %></dd>
  <dt><strong><%= model_class.human_attribute_name(:verbal_answer) %>:</strong></dt>
  <dd><%= @physical_exam.verbal_answer %></dd>
  <dt><strong><%= model_class.human_attribute_name(:motor_response) %>:</strong></dt>
  <dd><%= @physical_exam.motor_response %></dd>
  <dt><strong><%= model_class.human_attribute_name(:other_signs) %>:</strong></dt>
  <dd><%= @physical_exam.other_signs %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              physical_exams_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_physical_exam_path(@physical_exam), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              physical_exam_path(@physical_exam),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>